export type SpotDetail = {
  address: string;
  openingHours: string;
  openNote: string;
  reservationRequired: string;
  reservationMethod: string;
  reservationUrl: string | null;
  officialUrl: string | null;
  sourceUrl: string | null;
  description: string;
  verificationLevel: string;
  verificationNote: string;
  verifiedAt: string;
};

export const spotDetails: Record<string, SpotDetail> = {
  J01: {
    address: "江西省吉安市井冈山市茨坪镇红军南路5号1栋",
    openingHours: "周二至周日 08:00–17:00，16:30停止入馆",
    openNote: "周一闭馆（法定节假日通常除外）",
    reservationRequired: "个人一般免预约；团队按馆方规则预约",
    reservationMethod: "个人持有效证件参观；团队可使用馆方预约页面",
    reservationUrl: "https://jgsgmbwg.com/list/reservation",
    officialUrl: "https://www.jgsgmbwg.com/list/visit?num=0",
    sourceUrl: "https://www.jgstour.com/article/newsinfo/790/6",
    description: "井冈山革命博物馆是系统展示井冈山革命斗争史的专题博物馆，1959年建成开放。展陈以1927年至1930年前后井冈山革命根据地创建、巩固和发展为主线，通过革命文物、历史照片、文献档案、场景复原和多媒体手段，呈现秋收起义部队上井冈山、工农武装割据、朱毛会师、红四军建设等重要历史。馆藏资料丰富，是认识“农村包围城市、武装夺取政权”道路探索过程的重要窗口，也是井冈山红色教育体系中的核心场馆。",
    verificationLevel: "A",
    verificationNote: "地址、时段与馆方预约入口均有官方页面；个人免预约政策以最新现场公告为准。",
    verifiedAt: "2026-08-21",
  },
  J02: {
    address: "江西省吉安市井冈山市茨坪镇北山",
    openingHours: "常规参观建议 08:00–17:00",
    openNote: "纪念性园区；一般按景区白天接待时段开放",
    reservationRequired: "通常无需个人预约",
    reservationMethod: "现场参观；大型团队活动建议提前与井冈山景区/管理方联系",
    reservationUrl: null,
    officialUrl: "https://www.jgstour.com/article/newsinfo/816/6",
    sourceUrl: "https://www.jgstour.com/article/newsinfo/701/42",
    description: "井冈山革命烈士陵园位于茨坪北山，是缅怀井冈山斗争时期革命先烈的重要纪念设施。陵园以纪念堂、碑林、雕塑园、纪念碑等纪念空间构成完整的瞻仰序列，集中展示和纪念为创建、保卫井冈山革命根据地而牺牲的革命者。其空间庄重肃穆，既承担烈士纪念、祭扫和爱国主义教育功能，也常用于党团教育、入党宣誓等活动。与井冈山革命博物馆、茨坪革命旧址群相邻，适合作为理解井冈山斗争牺牲与信仰主题的重要节点。",
    verificationLevel: "A-",
    verificationNote: "井冈山官方景区政策明确该点免费；独立常规开放钟点未在单独页面稳定公开，按景区常规白天时段记录。",
    verifiedAt: "2026-08-21",
  },
  J03: {
    address: "江西省吉安市井冈山市茨坪镇挹翠湖周边（南山路、红军南路一带）",
    openingHours: "常规参观建议 08:00–17:00",
    openNote: "旧址群；一般按景区白天接待时段开放",
    reservationRequired: "通常无需个人预约",
    reservationMethod: "现场参观；部分旧址遇维护可能临时关闭",
    reservationUrl: null,
    officialUrl: "https://www.jgstour.com/article/newsinfo/790/6",
    sourceUrl: "https://www.jgstour.com/article/newsinfo/816/6",
    description: "茨坪革命旧址群是井冈山斗争时期党、政、军机关和领导人活动较为集中的旧址片区，主要分布在茨坪挹翠湖周边。这里保存或复原有毛泽东同志旧居以及前委、军部、军械处、公卖处等相关革命旧址，反映了红军在井冈山建立根据地后开展军事指挥、党的建设、后勤保障和群众工作的基本面貌。旧址多为赣西南民居形态，空间尺度亲切，与茨坪山城环境融为一体，适合与博物馆联动参观，从“实景旧址”理解井冈山根据地早期政权与军队运行。",
    verificationLevel: "A-",
    verificationNote: "旧址群为多个点位组合，无单一预约页；按井冈山官方景区常规管理口径。",
    verifiedAt: "2026-08-21",
  },
  J04: {
    address: "江西省吉安市井冈山市黄洋界景区",
    openingHours: "常规参观建议 08:00–17:00",
    openNote: "景区点位；以景区当日开放及观光车运行时间为准",
    reservationRequired: "需按井冈山景区票务规则购票/核验",
    reservationMethod: "通过井冈山官方景区渠道购票，现场实名核验",
    reservationUrl: "https://www.jgstour.com/article/service",
    officialUrl: "https://www.jgstour.com/article/raidersinfo/730/70",
    sourceUrl: "https://www.jgstour.com/article/newsinfo/790/6",
    description: "黄洋界位于井冈山北部，是井冈山五大哨口之一，也是井冈山革命斗争史上最具代表性的军事遗址。1928年8月，红军和地方群众在这里依托险要地形与工事取得黄洋界保卫战胜利，粉碎敌军进攻。毛泽东后来写下《西江月·井冈山》，使黄洋界成为井冈山精神的重要象征。现景区保留哨口工事、纪念碑、炮台及相关展示，并与挑粮小道等点位相连。这里兼具军事地形观察、革命史学习和自然山景体验，适合讲解“依靠群众、以少胜多”的斗争实践。",
    verificationLevel: "A-",
    verificationNote: "官方景区有介绍及购票指引；具体关门时间受交通和景区调度影响。",
    verifiedAt: "2026-08-21",
  },
  J05: {
    address: "江西省吉安市井冈山市茅坪镇茅坪村八角楼景区",
    openingHours: "常规参观建议 08:00–17:00",
    openNote: "景区旧址；以景区当日开放为准",
    reservationRequired: "需按井冈山景区票务规则购票/核验",
    reservationMethod: "通过井冈山官方景区渠道购票",
    reservationUrl: "https://www.jgstour.com/article/service",
    officialUrl: "https://www.jgstour.com/article/spot/346",
    sourceUrl: "https://www.jgstour.com/article/newsinfo/790/6",
    description: "八角楼位于井冈山市茅坪镇，是井冈山革命斗争时期的重要旧居和办公地点。1927年10月至1929年初，毛泽东曾在此居住和工作，并在艰苦条件下思考根据地建设问题。八角楼因楼顶开有八角形采光窗而得名，室内保留有床、桌椅等陈设，体现当年简朴的工作生活环境。这里与茅坪革命旧址群中的湘赣边界党代会会址、前委和特委旧址等共同构成根据地早期政治活动空间，是理解井冈山时期理论探索、党的建设和根据地治理的重要现场。",
    verificationLevel: "A-",
    verificationNote: "官方井冈山旅游网有独立景点介绍；开放钟点按景区常规白天时段记录。",
    verifiedAt: "2026-08-21",
  },
  J06: {
    address: "江西省吉安市井冈山市茨坪镇小井村（龙潭景区片区）",
    openingHours: "常规参观建议 08:00–17:00",
    openNote: "景区旧址；以龙潭/小井片区当日开放为准",
    reservationRequired: "需按井冈山景区票务规则购票/核验",
    reservationMethod: "通过井冈山官方景区渠道购票",
    reservationUrl: "https://www.jgstour.com/article/service",
    officialUrl: "https://www.jgstour.com/article/newsinfo/790/6",
    sourceUrl: "https://www.jgstour.com/article/newsinfo/511/6",
    description: "小井红军医院旧址展示井冈山斗争时期红军医疗卫生工作的艰苦起步。1928年前后，红军在小井建立较为正规的医院，为伤病员治疗和休养。医院建筑采用当地木构民居形式，条件简陋，却在药品、器械极其匮乏的情况下承担了大量救治任务。旧址后来遭破坏，现有建筑依据史料恢复，并配合医疗器具、图文和情景陈列讲述红军医护人员和群众共同救治伤员的历史。它与小井红军伤病员殉难处等遗址相互呼应，是理解井冈山后勤保障、军民关系和牺牲精神的重要点位。",
    verificationLevel: "A-",
    verificationNote: "官方景区介绍明确该点位；独立预约页不存在，随井冈山景区票务管理。",
    verifiedAt: "2026-08-21",
  },
  J07: {
    address: "江西省吉安市井冈山市茨坪镇大井村",
    openingHours: "常规参观建议 08:00–17:00",
    openNote: "景区旧址；以大井景区当日开放为准",
    reservationRequired: "需按井冈山景区票务规则购票/核验",
    reservationMethod: "通过井冈山官方景区渠道购票",
    reservationUrl: "https://www.jgstour.com/article/service",
    officialUrl: "https://www.jgstour.com/article/newsinfo/790/6",
    sourceUrl: "https://www.jgstour.com/article/newsinfo/816/6",
    description: "大井毛泽东同志旧居位于井冈山市大井村，是秋收起义部队进入井冈山后早期活动的重要旧址之一。1927年部队到达大井后，毛泽东曾在当地居住和办公；村中还保留与朱德、陈毅等革命活动相关的旧址。毛泽东旧居因外墙呈白色，当地常称“白屋”。建筑在战争中曾遭破坏，后按历史原貌修复，并保留部分旧墙等历史遗存。大井村兼具山地村落景观与革命旧址群特征，可帮助游客直观理解红军初上井冈山时期的驻地生活、群众联系和根据地开辟过程。",
    verificationLevel: "A-",
    verificationNote: "官方景区有最新介绍；具体闭馆钟点按景区统一管理。",
    verifiedAt: "2026-08-21",
  },
  J08: {
    address: "江西省吉安市井冈山市龙市镇会师广场/龙江书院片区",
    openingHours: "常规参观建议 08:00–17:00",
    openNote: "纪念馆/会师旧址片区；一般按白天开放",
    reservationRequired: "通常无需个人预约",
    reservationMethod: "现场参观；团队活动可提前联系景区",
    reservationUrl: null,
    officialUrl: "https://www.jgstour.com/article/newsinfo/816/6",
    sourceUrl: "https://www.celaj.gov.cn/col139/list.html",
    description: "井冈山会师纪念馆位于龙市镇朱毛会师历史发生地附近，重点讲述1928年朱德、陈毅率领的南昌起义和湘南起义部队与毛泽东领导的秋收起义部队在井冈山会师，以及随后组建中国工农革命军第四军的历史。展陈通常与会师广场、龙江书院等现场资源结合，呈现两支革命武装会合后在组织、军事和政治上的整合过程。该点位能够把井冈山从“建立落脚点”推进到“形成更强红军力量”的关键转折讲清楚，是井冈山军史教育的重要组成。",
    verificationLevel: "A-",
    verificationNote: "2026井冈山官方票务政策列该馆为免费点；无独立网页预约入口。",
    verifiedAt: "2026-08-21",
  },
  J09: {
    address: "江西省吉安市井冈山市黄洋界景区内（大陇镇源头村—黄洋界方向）",
    openingHours: "开放式山地步道，建议日间 08:00–17:00 游览",
    openNote: "无固定闭馆日；雨雪、地灾等情况可能临时管制",
    reservationRequired: "一般无需单独预约；进入关联景区按票务规则",
    reservationMethod: "按黄洋界/井冈山景区当天管理进入",
    reservationUrl: "https://www.jgstour.com/article/service",
    officialUrl: "https://www.jgstour.com/article/newsinfo/790/6",
    sourceUrl: "https://www.jgstour.com/article/raidersinfo/730/70",
    description: "挑粮小道是连接井冈山山上与山下粮食运输路线的代表性历史步道。井冈山斗争时期，面对敌军封锁和物资匮乏，红军官兵与群众常沿山路肩挑背驮，把粮食等物资运上井冈山。朱德与战士一起挑粮的故事使这条路广为人知。现保存和整理的体验路段与黄洋界景区相连，山势起伏明显，适合开展短程徒步和情景教学。其价值不在单一建筑，而在通过真实地形让参观者感受根据地时期物资保障的困难，以及官兵一致、艰苦奋斗的作风。",
    verificationLevel: "B+",
    verificationNote: "属线性户外遗址，无独立闭馆时间和预约页；应以天气和景区管制为准。",
    verifiedAt: "2026-08-21",
  },
  J10: {
    address: "江西省吉安市井冈山市柏露乡（柏露会议旧址、长富桥研学基地等片区，X864沿线）",
    openingHours: "开放式教育片区，建议白天参观",
    openNote: "无统一闭馆时间；具体旧址/研学点以现场为准",
    reservationRequired: "无统一个人预约页",
    reservationMethod: "团队红培通常由培训机构或基地组织联系",
    reservationUrl: null,
    officialUrl: "https://www.jgstour.com/article/newsinfo/377/6",
    sourceUrl: "https://www.jgstour.com/",
    description: "“柏露红色教育区”更接近柏露乡红色资源与研学点的组合性称呼，而不是一个拥有统一门禁、统一售票和统一开放时间的单体景区。柏露一带分布有革命旧址、会议旧址和红色研学基地，可与井冈山山上核心景区形成补充，侧重基层群众工作、红色交通和现场教学。对于平台数据，建议将其标记为“片区型/研学型资源”，并在二级页面继续拆分柏露会议旧址、长富桥研学基地等具体点位，这样更有利于路线排程、停留时间计算和后续预约管理。",
    verificationLevel: "B",
    verificationNote: "官方可确认柏露相关红色教育/研学资源，但“柏露红色教育区”非统一规范景区名，建议后续拆点。",
    verifiedAt: "2026-08-21",
  },
  Y01: {
    address: "江西省赣州市于都县渡江大道690号",
    openingHours: "周二至周日 08:30–17:30，17:00停止入馆",
    openNote: "周一闭馆（法定节假日除外）",
    reservationRequired: "实名预约，个人/团队可提前3天（含当天）预约",
    reservationMethod: "官方微信公众号“中央红军长征出发纪念馆”或官网预约页",
    reservationUrl: "https://www.ydczcfmuseum.cn/reservation",
    officialUrl: "https://www.yudu.gov.cn/yudu/ydly/202512/e6a56dbc879e478c8c920278c3d95d0e.shtml",
    sourceUrl: "https://www.ydczcfmuseum.cn/article/3426",
    description: "中央红军长征集结出发地纪念园位于于都河畔，是集中展示中央红军集结、渡河和踏上长征历史的核心景区。园区由东门渡口、中央红军长征出发纪念碑、游客中心、主题雕塑、新长征广场和中央红军长征出发纪念馆等组成。1934年10月，中央红军主力从于都地区集结并跨越于都河开始战略转移。纪念园通过纪念性空间、历史遗址和专题陈列把“集结—渡河—出发”串联起来，是于都红色旅游最重要的总入口，也适合作为长征主题路线的起点。",
    verificationLevel: "A",
    verificationNote: "2025年于都县文旅部门最新景区信息明确地址、时段与预约规则。",
    verifiedAt: "2026-08-21",
  },
  Y02: {
    address: "江西省赣州市于都县渡江大道690号（纪念园内）",
    openingHours: "周二至周日 08:30–17:30，17:00停止入馆",
    openNote: "周一闭馆（法定节假日除外）",
    reservationRequired: "实名预约",
    reservationMethod: "公众号或官网预约页",
    reservationUrl: "https://www.ydczcfmuseum.cn/reservation",
    officialUrl: "https://www.ydczcfmuseum.cn/index",
    sourceUrl: "https://www.yudu.gov.cn/yudu/ydly/202512/e6a56dbc879e478c8c920278c3d95d0e.shtml",
    description: "中央红军长征出发纪念馆是以中央红军长征集结出发史为核心内容的专题纪念馆，位于于都河东岸纪念园内。展览围绕中央苏区第五次反“围剿”后战略转移的历史背景、各部队在于都集结、群众筹粮筹款和架设浮桥、红军渡过于都河等内容展开，并通过文物、图片、文献、场景和多媒体手段再现长征出发过程。纪念馆与东门渡口、出发纪念碑形成“室内展陈+原址空间”的完整教学链条，是理解中央红军为何出发、如何出发以及苏区群众支援红军的重要场馆。",
    verificationLevel: "A",
    verificationNote: "官网与县政府均可核验；采用2025县政府的最新常规时段。",
    verifiedAt: "2026-08-21",
  },
  Y03: {
    address: "江西省赣州市于都县渡江大道690号中央红军长征集结出发地纪念园于都河畔",
    openingHours: "按纪念园常规参观时段 08:30–17:30；河岸开放空间以现场管理为准",
    openNote: "户外遗址，无独立闭馆日；纪念园周一馆舍闭馆",
    reservationRequired: "预约纪念园即可，无单独预约",
    reservationMethod: "同纪念园预约",
    reservationUrl: "https://www.ydczcfmuseum.cn/reservation",
    officialUrl: "https://www.yudu.gov.cn/yudu/ydly/202512/e6a56dbc879e478c8c920278c3d95d0e.shtml",
    sourceUrl: "https://www.yudu.gov.cn/yudu/jryd/202601/535ff091833f4653a68d75d5f3262f19.shtml",
    description: "东门渡口位于于都县城东门外于都河畔，是中央红军长征出发地旧址的重要组成部分。1934年10月中央机关、中央军委以及红军部队在于都地区完成集结后，从多个渡口跨越于都河，东门渡口是最具代表性的原址之一。今天的渡口保留河岸空间，并与纪念碑、纪念馆和纪念园景观连成一体。站在河边可以直观看到当年渡河所面对的水域环境，因此特别适合开展“告别苏区、踏上长征”的情景讲解和仪式教学，是于都长征主题路线中最具现场感的节点之一。",
    verificationLevel: "A-",
    verificationNote: "户外原址没有独立“闭馆时间”，数据表采用纪念园管理时段作为可执行参观口径。",
    verifiedAt: "2026-08-21",
  },
  Y04: {
    address: "江西省赣州市于都县渡江大道690号中央红军长征集结出发地纪念园内",
    openingHours: "按纪念园常规参观时段 08:30–17:30",
    openNote: "户外纪念设施；无独立闭馆日",
    reservationRequired: "预约纪念园即可，无单独预约",
    reservationMethod: "同纪念园预约",
    reservationUrl: "https://www.ydczcfmuseum.cn/reservation",
    officialUrl: "https://www.yudu.gov.cn/yudu/ydly/202512/e6a56dbc879e478c8c920278c3d95d0e.shtml",
    sourceUrl: "https://www.yudu.gov.cn/yudu/jryd/202509/3fe5ca8b52374996b8b62487c31ff810.shtml",
    description: "中央红军长征出发纪念碑位于于都河畔纪念园核心位置，是纪念中央红军从于都集结出发长征的重要标志性建筑。纪念碑与东门渡口、纪念馆、新长征广场共同形成纪念园的空间主轴，承担瞻仰、献花、主题教育和大型纪念活动功能。参观时可先通过纪念碑建立历史时间和事件概念，再前往渡口感受原址环境，最后进入纪念馆系统了解长征出发背景与过程。对红培路线而言，这里适合安排简短仪式、集体合影和主题导入，是组织化教学最便利的节点之一。",
    verificationLevel: "A-",
    verificationNote: "户外纪念设施，无独立预约或闭馆时间。",
    verifiedAt: "2026-08-21",
  },
  Y05: {
    address: "江西省赣州市于都县贡江镇解放社区建国路3号附近（葛氏宗祠）",
    openingHours: "建议周二至周日 08:30–17:30 内参观；以旧址现场开放为准",
    openNote: "旧址型场馆，未见稳定独立开放公告",
    reservationRequired: "无独立网页预约；团队建议联系于都中央红军长征集结出发历史博物馆",
    reservationMethod: "电话/馆方统筹预约",
    reservationUrl: null,
    officialUrl: "https://www.ydczcfmuseum.cn/article/1106",
    sourceUrl: "https://www.yudu.gov.cn/yudu/ydly/202203/88c63f48e79b424a85d28c17276be7f6.shtml",
    description: "红四军军部旧址设于葛氏宗祠，是于都县城重要革命旧址之一。红四军在赣南闽西活动期间曾在于都驻扎，军部机关在这里开展军事和政治工作，反映了红军主力在赣南地区转战、整训和发动群众的历史。葛氏宗祠本身为传统宗祠建筑，革命时期被赋予新的军政功能，体现了苏区时期党和红军利用乡村公共建筑开展工作的特点。现旧址结合史料陈列和民俗展示，可与县城内赣南省委、赣南省苏维埃政府等旧址组成“于都苏区政权与红军活动”专题线路。",
    verificationLevel: "B+",
    verificationNote: "官方可核实旧址与地址；单独最新开放时段未稳定发布，建议上线前再电话复核。",
    verifiedAt: "2026-08-21",
  },
  Y06: {
    address: "江西省赣州市于都县贡江镇环城东路18号",
    openingHours: "建议周二至周日 08:30–17:30 内参观；以现场开放为准",
    openNote: "旧址型场馆，未见独立常规开放公告",
    reservationRequired: "无独立网页预约；团队建议联系馆方",
    reservationMethod: "电话/馆方统筹预约",
    reservationUrl: null,
    officialUrl: "https://www.jxnews.com.cn/xds/system/2021/04/16/019249471.shtml",
    sourceUrl: "https://www.yudu.gov.cn/yudu/tzgg/202607/5262c0ddacfd4300bb463dd795f34cdb.shtml",
    description: "中共赣南省委旧址位于于都县城环城东路，是中央苏区时期赣南地方党组织开展工作的历史见证。赣南省委承担领导区域党的建设、动员群众、支援红军和配合苏区政权建设等任务，在中央苏区地方治理体系中具有重要位置。旧址依托原有历史建筑保存和展示，通过文字、图片与复原陈设呈现赣南党组织在革命战争环境下开展组织、宣传和群众工作的情况。它与赣南省苏维埃政府旧址距离较近，适合组合成一段紧凑的县城步行教学线路，用于解释“地方党委—苏维埃政权—红军”之间的协同关系。",
    verificationLevel: "B+",
    verificationNote: "地址有党史权威来源；开放时段缺乏独立最新公告，数据采用可执行建议时段并明确现场为准。",
    verifiedAt: "2026-08-21",
  },
  Y07: {
    address: "江西省赣州市于都县贡江镇向阳社区北门西段1号（何屋）",
    openingHours: "周二至周日 08:30–17:30，17:00停止入馆（按馆方管理口径）",
    openNote: "周一闭馆（法定节假日除外）",
    reservationRequired: "实名预约/按馆方统一管理",
    reservationMethod: "可通过中央红军长征出发纪念馆预约体系或电话咨询",
    reservationUrl: "https://www.ydczcfmuseum.cn/reservation",
    officialUrl: "https://www.yudu.gov.cn/yudu/ydly/202407/4ef26b4f06eb4e8c82af2db8e36644c9.shtml",
    sourceUrl: "https://www.yudu.gov.cn/yudu/ydrw/202212/48f87dfc1f704084b98f08598490d80e.shtml",
    description: "赣南省苏维埃政府旧址俗称“何屋”，是中央苏区时期赣南地方苏维埃政权的重要办公旧址。这里保存了地方革命政权在战争环境下组织生产、支前、土地和社会事务等工作的历史记忆，同时也是长征前夕重要革命活动发生地之一。旧址采用赣南传统民居建筑形态，内部通过复原陈设和图文资料呈现苏维埃政府机构设置与工作场景。于都中央红军长征出发纪念馆曾将该旧址纳入统一开放管理，因此可与长征出发纪念园、赣南省委旧址等组合，形成从苏区地方政权到中央红军战略转移的历史链条。",
    verificationLevel: "A-",
    verificationNote: "于都县政府恢复开放公告明确该旧址纳入纪念馆开放管理，可据此采用馆方常规时段。",
    verifiedAt: "2026-08-21",
  },
  Y08: {
    address: "江西省赣州市于都县祁禄山镇红军小镇及周边山地路段",
    openingHours: "开放式户外步道，建议日出后至日落前游览",
    openNote: "无固定闭馆日；恶劣天气、地灾风险时可能临时封闭",
    reservationRequired: "无需预约",
    reservationMethod: "现场进入；团队研学建议由当地文旅/培训机构组织",
    reservationUrl: null,
    officialUrl: "https://www.yudu.gov.cn/ydxxxgk/fzgh/202108/171e75d81fc24814b5f9f3e345424003/files/b4822c0dcd034d9a9526f974db4f2a5a.pdf",
    sourceUrl: "https://www.yudu.gov.cn/yudu/ydrw/202508/e94ecbc6c29a46ac9190b0a6b7329cde.shtml",
    description: "祁禄山红军小道位于于都南部山区，是当地依托红军长征前后活动线路和山地交通遗迹打造的红色徒步体验资源。与纪念馆式场馆不同，小道的核心价值是“走路体验”：通过山岭、村落和旧交通路径，让参与者直观感受当年红军在赣南山区行军、转移和联系群众的地理条件。祁禄山镇近年来将红军小道与红军小镇、红色村落、研学课程等结合，适合安排半日或短程徒步教学。平台应把它作为线性户外资源管理，重点记录里程、坡度、天气风险、补给点和团队安全要求，而不是套用博物馆闭馆逻辑。",
    verificationLevel: "B",
    verificationNote: "官方规划确认红军小道与红军小镇建设；无统一门禁和预约页。",
    verifiedAt: "2026-08-21",
  },
  Y09: {
    address: "江西省赣州市于都县境内长征国家文化公园相关线路（沙心—宽田—段屋—梓山—县城—新陂—利村—小溪—祁禄山等段）",
    openingHours: "开放式线性步道，原则上白天游览",
    openNote: "无统一闭馆日；不同路段受施工、天气和村道条件影响",
    reservationRequired: "无需统一预约",
    reservationMethod: "分段进入；团队需按具体路段制定交通和安全方案",
    reservationUrl: null,
    officialUrl: "https://www.yudu.gov.cn/ydxxxgk/fzgh/202108/171e75d81fc24814b5f9f3e345424003/files/b4822c0dcd034d9a9526f974db4f2a5a.pdf",
    sourceUrl: "https://www.yudu.gov.cn/yudu/ydly/202507/a425e15f8fc54523abd914cbb8cac823.shtml",
    description: "于都长征历史步道不是一个单点景区，而是长征国家文化公园建设背景下串联于都多个乡镇、红色旧址、渡口和村落的线性文化线路。相关规划将沙心、宽田、段屋、梓山、县城、新陂、利村、小溪、祁禄山等区域纳入长征步道网络，以原有交通路径、革命遗址和乡村道路共同构建“可行走的长征史”。其适合用于分段徒步、骑行和研学，不适合给出统一开闭馆时间。对路线优化平台而言，应拆分为若干可计算路段，分别配置里程、预计耗时、海拔、补给、车辆接驳和安全等级。",
    verificationLevel: "B",
    verificationNote: "官方规划层面权威，但线路较长且持续建设，建议平台按具体可开放路段二次核验。",
    verifiedAt: "2026-08-21",
  },
  Y10: {
    address: "江西省赣州市于都县梓山镇潭头村",
    openingHours: "开放式村落，全天可进入；游客服务与展陈建议 08:30–17:30 内安排",
    openNote: "无统一闭馆日",
    reservationRequired: "无需统一预约",
    reservationMethod: "自由参观；团队体验、讲解、用餐可联系当地运营主体",
    reservationUrl: null,
    officialUrl: "https://www.yudu.gov.cn/yudu/ydly/202411/08d520239d124125adb437906ffb3400.shtml",
    sourceUrl: "https://www.yudu.gov.cn/yudu/ydly/202507/a425e15f8fc54523abd914cbb8cac823.shtml",
    description: "潭头村位于于都县梓山镇，是于都近年来乡村旅游和红色研学路线中常见的乡村振兴体验点。村庄依托赣南乡村风貌、富硒农业和本地生产生活场景发展观光、研学、农事体验和餐饮服务，并与于都长征出发地等红色资源形成“红色教育+乡村发展”组合。它本身不是封闭式纪念馆，因此更适合用于路线中的午餐、休整、基层治理和乡村振兴主题教学。平台排程时可把核心村落游览控制在1至2小时，并把具体体验项目、团队接待能力和餐饮预订作为可选资源配置。",
    verificationLevel: "A-",
    verificationNote: "县政府文旅线路持续将潭头村纳入推荐路线；村落本身无统一开闭馆与预约。",
    verifiedAt: "2026-08-21",
  },
  R01: {
    address: "江西省赣州市瑞金市叶坪镇叶坪村",
    openingHours: "常规 08:40–17:00",
    openNote: "旧址景区全年开放；以管理处当日公告为准",
    reservationRequired: "未见独立个人网页预约要求",
    reservationMethod: "现场参观；团队可联系瑞金中央革命根据地纪念馆管理处",
    reservationUrl: null,
    officialUrl: "https://www.rjjng.com.cn/jiuzhi.thtml?id=10955",
    sourceUrl: "https://www.rjjng.com.cn/",
    description: "叶坪革命旧址群是中央苏区时期最重要的革命旧址群之一。1931年11月，中华苏维埃第一次全国代表大会在叶坪召开，中华苏维埃共和国临时中央政府成立，叶坪由此成为中央苏区早期党政军机关高度集中的区域。旧址群保存有第一次全国苏维埃代表大会会址、临时中央政府旧址、红军烈士纪念塔等多处全国重点文物保护单位。建筑多为祠堂、民居等传统乡土空间，见证了革命政权由根据地治理向较系统国家政权实践的发展，是理解中央苏区政权建设和制度探索的核心现场。",
    verificationLevel: "A",
    verificationNote: "瑞金中央革命根据地纪念馆官网有独立旧址页面；总馆官网公布常规开放时段。",
    verifiedAt: "2026-08-21",
  },
  R02: {
    address: "江西省赣州市瑞金市沙洲坝镇沙洲坝村",
    openingHours: "常规 08:40–17:00",
    openNote: "旧址景区全年开放；以当日公告为准",
    reservationRequired: "未见独立个人网页预约要求",
    reservationMethod: "现场参观；团队可联系管理处",
    reservationUrl: null,
    officialUrl: "https://www.rjjng.com.cn/jiuzhi2.thtml?id=10956&pn=3",
    sourceUrl: "https://www.rjjng.com.cn/",
    description: "沙洲坝红井革命旧址群位于瑞金城西沙洲坝，是中央苏区后期中央机关活动的重要区域。“红井”与毛泽东关心群众饮水问题的故事密切相关，成为中央苏区群众路线和为民办实事的经典教育载体。旧址群除红井外，还分布有中央政府机关及相关革命旧址，保留大量赣南传统建筑。参观通常以红井故事为入口，再延伸到中央机关工作和苏区群众生活，使抽象的群众路线通过一口井、一个村落变得具体可感。这里适合与“二苏大”旧址群和中央革命根据地历史博物馆组合参观。",
    verificationLevel: "A",
    verificationNote: "官网有独立旧址页，开放时间采用纪念馆管理处统一常规时段。",
    verifiedAt: "2026-08-21",
  },
  R03: {
    address: "江西省赣州市瑞金市象湖镇城西龙珠路1号",
    openingHours: "08:40–17:00，具体停止入馆时间以馆方公告为准",
    openNote: "周一闭馆检修（法定节假日通常除外）",
    reservationRequired: "未见稳定独立网页预约入口；免费开放政策以馆方为准",
    reservationMethod: "现场参观/团队电话咨询",
    reservationUrl: null,
    officialUrl: "https://www.rjjng.com.cn/gaikuang.thtml?id=10928",
    sourceUrl: "https://www.rjjng.com.cn/",
    description: "中央革命根据地历史博物馆是系统展示中央苏区和中华苏维埃共和国历史的重要专题博物馆，也是瑞金红色资源的综合性总馆。展览从革命根据地形成、中央苏区发展、苏维埃政权建设、红军反“围剿”、社会经济文化建设等多个方面展开，通过文物、文献、图片、模型和场景复原呈现中央苏区历史。与叶坪、沙洲坝、“二苏大”等原址相比，博物馆更适合承担背景梳理和知识整合功能。路线设计中可安排在旧址参观前作导入，或在多个旧址之后作系统总结，以增强历史线索的完整性。",
    verificationLevel: "A",
    verificationNote: "瑞金纪念馆官网公布总馆地址和统一开放时间；周一馆舍闭馆检修。",
    verifiedAt: "2026-08-21",
  },
  R04: {
    address: "江西省赣州市瑞金市沙洲坝镇沙洲坝村（中华苏维埃共和国临时中央政府大礼堂旧址片区）",
    openingHours: "常规 08:40–17:00",
    openNote: "旧址景区全年开放；以当日公告为准",
    reservationRequired: "未见独立个人网页预约要求",
    reservationMethod: "现场参观；团队联系管理处",
    reservationUrl: null,
    officialUrl: "https://www.rjjng.com.cn/news-content.thtml?id=10536",
    sourceUrl: "https://www.rjjng.com.cn/",
    description: "“二苏大”革命旧址群以中华苏维埃共和国第二次全国苏维埃代表大会相关旧址为核心。1934年1月，第二次全国苏维埃代表大会在瑞金沙洲坝召开，大会总结中央苏区政权建设经验并对政府机构等作出调整。最具代表性的中央政府大礼堂采用当时条件下较有特色的建筑形式，是中央苏区大型政治会议空间的实物见证。周边还分布与中央机关活动有关的旧址。该点位适合讲解苏维埃政权制度实践、中央苏区治理体系和长征前夕政治军事形势，并可与红井旧址群形成较紧凑的沙洲坝片区半日路线。",
    verificationLevel: "A-",
    verificationNote: "官方纪念馆网站有相关介绍；统一按旧址景区时段管理。",
    verifiedAt: "2026-08-21",
  },
  R05: {
    address: "江西省赣州市瑞金市叶坪镇洋溪村",
    openingHours: "常规 08:40–17:00",
    openNote: "旧址类点位全年开放；以现场管理为准",
    reservationRequired: "未见独立个人网页预约要求",
    reservationMethod: "现场参观；团队联系管理处",
    reservationUrl: null,
    officialUrl: "https://www.rjjng.com.cn/jz-content.thtml?cid=11127&id=20683",
    sourceUrl: "https://www.rjjng.com.cn/",
    description: "中央革命军事委员会旧址位于瑞金叶坪洋溪村，是中央苏区时期最高军事领导机关的重要历史遗址。1931年中华苏维埃共和国成立后，中央革命军事委员会承担红军建设、作战指挥和军事行政等重要职能，是理解中央苏区军队指挥体系的重要节点。旧址依托当地宗祠建筑设置机关，体现革命机关因地制宜使用乡村建筑的历史特征。参观这里可以把叶坪的政权成立史进一步延伸到军队领导与军事决策体系，尤其适合红培课程中讲解党对军队领导、红军组织建设和中央苏区军事斗争。",
    verificationLevel: "A",
    verificationNote: "瑞金中央革命根据地纪念馆官网有该旧址专题页面。",
    verifiedAt: "2026-08-21",
  },
  R06: {
    address: "江西省赣州市瑞金市象湖镇城西龙珠路1号附近（中央革命根据地历史博物馆片区）",
    openingHours: "常规 08:40–17:00",
    openNote: "纪念园户外空间全年开放；馆舍部分受周一闭馆影响",
    reservationRequired: "未见独立预约要求",
    reservationMethod: "现场参观",
    reservationUrl: null,
    officialUrl: "https://www.rjjng.com.cn/gaikuang.thtml?id=10928",
    sourceUrl: "https://www.rjjng.com.cn/",
    description: "中华苏维埃纪念园是瑞金以中华苏维埃共和国和中央苏区历史为主题建设的纪念性公共空间，与中央革命根据地历史博物馆及周边红色文化设施相互衔接。园区通过纪念性建筑、雕塑、景观轴线和主题展示，概括中央苏区政权建设、红军斗争和苏区群众支援革命的历史。相比叶坪、沙洲坝等原址，纪念园更偏向综合纪念与公共教育，空间开阔，适合团队集散、主题仪式和短时教学。路线设计中可作为博物馆参观的前后衔接点，也可用于红色研学的开班、总结或集体活动。",
    verificationLevel: "A-",
    verificationNote: "与中央革命根据地历史博物馆同属管理体系；户外纪念园无独立预约页。",
    verifiedAt: "2026-08-21",
  },
  N01: {
    address: "江西省南昌市西湖区中山路380号",
    openingHours: "周二至周日 09:00–17:00，16:30停止入馆",
    openNote: "周一闭馆（法定节假日及特别公告除外）",
    reservationRequired: "实名预约参观",
    reservationMethod: "官方微信公众号/微信小程序及支付宝小程序“南昌八一起义纪念馆”",
    reservationUrl: null,
    officialUrl: "https://www.nc.gov.cn/ncszf/rwfg/202208/ae5ef257ee2049e8842d2b2e7b0db2c7.shtml",
    sourceUrl: "https://tt.jxnews.com.cn/news/2766033",
    description: "南昌八一起义纪念馆以1927年8月1日南昌起义为主题，馆址核心为当年起义总指挥部所在地江西大旅社。纪念馆1956年筹建、1959年开放，所辖南昌起义总指挥部旧址、贺龙指挥部旧址、叶挺指挥部旧址、朱德军官教育团旧址和朱德旧居等革命旧址被列为全国重点文物保护单位。基本陈列通过历史文物、图片、文献和场景展示起义的背景、组织、战斗经过及历史影响，是理解人民军队创建史的标志性场馆。由于客流大，平台应重点标注实名预约和高峰期票源规则。",
    verificationLevel: "A",
    verificationNote: "2026南昌市政府页面确认场馆现状；预约制度以馆方公告为准。",
    verifiedAt: "2026-08-21",
  },
  N02: {
    address: "江西省南昌市西湖区八一广场",
    openingHours: "户外广场全天开放；夜间灯光及局部管理以现场为准",
    openNote: "无固定闭馆日",
    reservationRequired: "无需预约",
    reservationMethod: "自由参观",
    reservationUrl: null,
    officialUrl: "https://www.nc.gov.cn/ncszf/whtya/201812/dc1e84f8c5d54d279857ea64933a16cc.shtml",
    sourceUrl: "https://www.nc.gov.cn/",
    description: "八一南昌起义纪念塔矗立于南昌八一广场，是城市最具代表性的革命纪念地标之一。纪念塔为纪念1927年南昌起义而建，塔体以庄重挺拔的纪念性造型强调“军旗升起的地方”这一城市记忆，并通过浮雕、题字等形式表现起义历史。它与八一广场共同构成开放式城市公共空间，不属于封闭式博物馆，因此通常没有预约和固定闭馆时间。对路线设计而言，纪念塔适合安排夜间或早晚短时打卡，也可与中山路的八一起义纪念馆组合成步行线路，分别承担“城市象征”和“系统展陈”两种功能。",
    verificationLevel: "A-",
    verificationNote: "南昌市政府文保名录明确位置与文保属性；作为广场户外纪念设施无统一开闭馆。",
    verifiedAt: "2026-08-21",
  },
  N03: {
    address: "江西省南昌市西湖区象山南路119号",
    openingHours: "周二至周日 09:00–17:00，16:30左右停止入馆/取票",
    openNote: "周一闭馆（法定节假日及公告除外）",
    reservationRequired: "个人免预约；团队提前预约",
    reservationMethod: "个人凭有效证件领取当日票；团队预约电话0791-86214160",
    reservationUrl: null,
    officialUrl: "https://www.ncn4a.cn/xhgk/1.html",
    sourceUrl: "https://www.ncn4a.cn/xhxx_1/128.html",
    description: "南昌新四军军部旧址陈列馆位于象山南路，馆区包括南昌新四军军部旧址、中共中央东南分局旧址、陈列大楼和纪念广场。1938年1月，新四军军部在南昌正式运转，在此完成南方八省红军和游击队改编组建并陆续开赴抗日前线的重要工作。基本陈列《铁军出征》以南方游击战争、谈判改编、汇聚南昌和驰骋华中为主线，配合两处全国重点文物保护单位原址展示新四军组建历史。该馆2024年底曾改陈闭馆，后已恢复开放，平台不应继续沿用旧闭馆信息。",
    verificationLevel: "A",
    verificationNote: "官网2025-09后已发布恢复开放及2026多项开放公告；个人免预约政策有正式公告。",
    verifiedAt: "2026-08-21",
  },
  N04: {
    address: "江西省南昌市东湖区子固路165号",
    openingHours: "周二至周日 09:00–17:00，16:30左右停止入馆",
    openNote: "周一闭馆（法定节假日及馆方公告除外）",
    reservationRequired: "按南昌八一起义纪念馆统一预约/管理规则",
    reservationMethod: "通过“南昌八一起义纪念馆”官方预约渠道",
    reservationUrl: null,
    officialUrl: "https://www.nc.gov.cn/ncszf/rwfg/202208/ae5ef257ee2049e8842d2b2e7b0db2c7.shtml",
    sourceUrl: "https://wgxj.nc.gov.cn/wgxlj/zfcg/202201/674656e5f03b4f318e63013c8dcec781.shtml",
    description: "贺龙指挥部旧址是南昌八一起义纪念馆所辖五处重要革命旧址之一。1927年南昌起义前后，贺龙所部及相关指挥机关曾在这里活动，旧址见证了起义部队的组织、部署和战斗准备。建筑本身保留近代南昌城市建筑特征，内部以复原陈列和史料展示为主，使参观者能从总指挥部之外看到起义军不同指挥系统的空间分布。该点距离八一起义纪念馆不远，适合设计成城市红色步行路线的一站，通过“总指挥部—贺龙指挥部—八一广场纪念塔”串联起义史与城市空间。",
    verificationLevel: "A-",
    verificationNote: "由南昌八一起义纪念馆体系管理；当前门牌采用子固路165号。",
    verifiedAt: "2026-08-21",
  },
  A01: {
    address: "江西省萍乡市安源区安源镇安源路矿工人运动纪念馆景区",
    openingHours: "常规周二至周日 09:00–17:00（以馆方当天公告为准）",
    openNote: "一般周一闭馆；法定节假日可能调整",
    reservationRequired: "个人通常免费参观；团队预约",
    reservationMethod: "团队预约热线0799-6353658",
    reservationUrl: null,
    officialUrl: "https://www.ayjng.cn/nd.jsp?id=51",
    sourceUrl: "https://www.ayjng.cn/",
    description: "安源路矿工人运动纪念馆创建于1956年，是系统研究和展示安源工人运动史的专题纪念馆。安源是中国共产党早期开展工人运动的重要地区，1921年起毛泽东、李立三、刘少奇等先后来到安源开展工作，1922年安源路矿工人大罢工成为中国工运史上的重要事件。馆区除陈列大楼外，还负责保护安源路矿工人俱乐部、谈判处、工人补习夜校等大量革命旧址。通过馆藏文物、历史照片和复原陈列，可以系统理解党在产业工人中开展组织、教育、经济合作和政治斗争的实践。",
    verificationLevel: "A-",
    verificationNote: "馆方官网权威，团队预约电话明确；常规钟点需以最新现场公告复核，表内采用最一般时段。",
    verifiedAt: "2026-08-21",
  },
  A02: {
    address: "江西省萍乡市安源区安源镇半边街广场（罢工后俱乐部旧址；另有牛角坡52号罢工前旧址）",
    openingHours: "常规周二至周日 09:00–17:00（按纪念馆旧址管理时段参考）",
    openNote: "一般周一闭馆/维护；以现场为准",
    reservationRequired: "通常无需个人独立预约；团队联系纪念馆",
    reservationMethod: "团队预约热线0799-6353658",
    reservationUrl: null,
    officialUrl: "https://www.ayjng.cn/nd.jsp?id=51",
    sourceUrl: "https://www.ayjng.cn/",
    description: "安源路矿工人俱乐部旧址是安源工人运动最核心的实物遗存之一。1922年安源路矿工人俱乐部成立后，成为组织工人、开展教育和维护工人权益的重要机构，并在安源路矿工人大罢工中发挥关键作用。现安源有罢工前后两处与俱乐部相关的重要旧址：牛角坡52号旧址和半边街广场一带的罢工后旧址。用户清单中的“工人俱乐部旧址”建议在平台中明确具体子点，否则导航可能产生歧义。参观可与纪念馆、谈判处和工人补习学校旧址组合，形成完整的工运史现场教学链条。",
    verificationLevel: "A-",
    verificationNote: "官方馆方资料明确两处俱乐部旧址；建议平台拆分“罢工前/罢工后”两个子点。",
    verifiedAt: "2026-08-21",
  },
  A03: {
    address: "江西省萍乡市安源区建设中路秋收起义广场",
    openingHours: "开放式城市广场，全天开放",
    openNote: "无固定闭馆日",
    reservationRequired: "无需预约",
    reservationMethod: "自由参观；大型活动按城市公共空间管理",
    reservationUrl: null,
    officialUrl: "https://www.pxdx.org.cn/jxzy/620.html",
    sourceUrl: "https://www.ayjng.cn/",
    description: "秋收起义广场是萍乡市中心具有鲜明红色主题的城市公共空间，以纪念湘赣边界秋收起义和安源作为秋收起义策源地之一的历史为核心。广场通过纪念碑、雕塑、轴线景观和城市公共空间表达革命主题，既承担市民休闲功能，也承担纪念活动和红色教育功能。与安源路矿工人运动纪念馆相比，它更适合作为城市形象和主题仪式节点，没有博物馆式闭馆和预约要求。路线设计时可在到达萍乡或离开安源前安排30分钟左右停留，用于主题导入、集体合影或简短讲解。",
    verificationLevel: "B+",
    verificationNote: "属于开放式广场，无预约；历史主题可由安源纪念馆及当地党校资料交叉核验。",
    verifiedAt: "2026-08-21",
  },
  S01: {
    address: "江西省上饶市信州区陵园路66号（导航常标叶挺南大道66号）",
    openingHours: "常规约 09:00–16:30；2026暑期曾延时至17:30，本表不采用暑期延时",
    openNote: "周一闭馆（法定节假日除外）",
    reservationRequired: "未发现独立网页预约；一般现场参观",
    reservationMethod: "团体/服务咨询0793-8153595",
    reservationUrl: null,
    officialUrl: "https://m.aiyoushangrao.com/bads/222797/",
    sourceUrl: "https://jxsr.jxnews.com.cn/system/2025/04/29/020857803.shtml",
    description: "上饶集中营革命烈士纪念馆以1941年皖南事变后国民党在上饶设立集中营、囚禁新四军干部和爱国进步人士的历史为主题。馆内通过文物、照片、档案、场景复原等方式展示集中营的形成、残酷迫害以及被囚革命者在狱中坚持斗争、举行茅家岭暴动和赤石暴动等历史。纪念馆与革命烈士陵园、茅家岭监狱旧址共同构成核心参观区。纪念馆2025年曾闭馆改造，2026年已恢复并发布暑期开放公告，因此平台应采用恢复后的状态，并将季节性延时与常规时段分开。",
    verificationLevel: "A-",
    verificationNote: "2025改造公告来自名胜区管理委员会；2026已恢复开放。常规钟点以当前景区公开信息交叉核验。",
    verifiedAt: "2026-08-21",
  },
  S02: {
    address: "江西省上饶市信州区茅家岭街道茅家岭村（上饶集中营名胜区内）",
    openingHours: "常规约 09:00–16:30；以名胜区当日开放为准",
    openNote: "周一一般闭馆/维护；法定节假日除外",
    reservationRequired: "无独立网页预约",
    reservationMethod: "现场参观；团体咨询0793-8153595",
    reservationUrl: null,
    officialUrl: "https://m.aiyoushangrao.com/bads/222797/",
    sourceUrl: "https://jxsr.jxnews.com.cn/system/2025/04/29/020857803.shtml",
    description: "茅家岭监狱旧址是上饶集中营保存最具现场感的监狱遗址之一。旧址原为当地庙宇建筑，后被国民党特务机关改作秘密监狱，曾关押共产党人、新四军干部和抗日爱国进步人士。监狱内部空间狭窄压抑，并留有审讯、关押等历史痕迹，是理解上饶集中营残酷统治的重要实物证据。1942年发生的茅家岭暴动，是被囚革命者反抗迫害的重要事件。参观该点建议与革命烈士纪念馆和陵园连线，由纪念馆提供背景，再通过原址空间强化历史感受。",
    verificationLevel: "A-",
    verificationNote: "2025纪念馆改造期间官方明确茅家岭旧址仍开放，说明其为独立可参观点；常规时段随名胜区管理。",
    verifiedAt: "2026-08-21",
  },
  S03: {
    address: "江西省上饶市弋阳县弋江镇城北峨眉嘴山顶（北路69号一带）",
    openingHours: "周二至周日 09:00–11:30、14:30–17:00",
    openNote: "周一闭馆（法定节假日可能调整）",
    reservationRequired: "通常免费参观；团队可电话预约",
    reservationMethod: "咨询/预约电话0793-5883171；未见独立官方网页预约",
    reservationUrl: null,
    officialUrl: "https://www.dswxyjy.org.cn/n/2012/1015/c222137-19265382.html",
    sourceUrl: "https://www.fzmcta.com/content-202012080856093326.html",
    description: "方志敏纪念馆位于方志敏烈士家乡弋阳县，以方志敏的革命生涯、赣东北革命根据地建设和狱中文稿等历史为主要展示内容。方志敏是赣东北、闽浙赣革命根据地的重要创建者和领导人，1935年在南昌英勇就义，其《可爱的中国》《清贫》等作品影响深远。纪念馆通过文献、照片、实物和主题陈列梳理其从青年求学、投身革命到创建根据地、北上抗日先遣队和狱中斗争的经历。与弋阳方志敏故居、革命旧址结合，可形成较完整的方志敏主题红色教育线路。",
    verificationLevel: "A-",
    verificationNote: "历史内容有中央党史和方志敏干部学院等权威来源；开放时段建议出发前电话复核。",
    verifiedAt: "2026-08-21",
  },
  XG1: {
    address: "江西省赣州市兴国县将军大道与文明大道交汇处",
    openingHours: "08:30–17:30",
    openNote: "周一闭馆",
    reservationRequired: "未见强制个人预约；团队可联系园区",
    reservationMethod: "咨询电话0797-5318997",
    reservationUrl: null,
    officialUrl: "https://www.xingguo.gov.cn/xgxxxgk/c116842/202602/e530b3edb29b42b0bf8cd4d1ca18bed7.shtml",
    sourceUrl: "https://www.xingguo.gov.cn/xgxxxgk/xg91019/202406/2c7dcafbb025443b86bde76e93ae04cb.shtml",
    description: "兴国将军园现与苏区干部好作风纪念园形成一体化红色教育景区，是展示“将军县”兴国革命贡献的重要窗口。园内设置将军馆、苏区干部好作风陈列馆、将军广场、主题群雕、国防教育空间和园林景观，通过人物事迹、文物资料和纪念性空间集中呈现兴国籍开国将军、革命烈士以及苏区干部群体的历史贡献。兴国在中央苏区时期参军支前人数众多，因此这里不仅讲“将军个人”，也强调苏区群众和干部作风。适合作为兴国红色路线的总览点和团队集散点。",
    verificationLevel: "A",
    verificationNote: "2026兴国县文旅部门A级景区名录给出地址、电话、08:30–17:30及周一闭馆。",
    verifiedAt: "2026-08-21",
  },
  XG2: {
    address: "江西省赣州市兴国县长冈乡长冈村",
    openingHours: "周二至周日 08:30–12:00、14:30–17:30",
    openNote: "周一闭馆",
    reservationRequired: "未见独立网页预约；团队可联系兴国革命纪念馆",
    reservationMethod: "0797-5322604（兴国革命纪念馆）",
    reservationUrl: null,
    officialUrl: "https://www.xingguo.gov.cn/xgxxxgk/xg91019/202406/2c7dcafbb025443b86bde76e93ae04cb.shtml",
    sourceUrl: "https://www.xingguo.gov.cn/xgzf/c114397/list_4.shtml",
    description: "长冈乡调查纪念馆以毛泽东在中央苏区时期开展《长冈乡调查》的历史为主题。1930年代，毛泽东通过深入基层调查长冈乡苏维埃政府和群众工作，总结干部密切联系群众、解决实际问题的经验，并形成具有重要影响的调查材料。纪念馆通过史料、图片、复原场景和当地历史资源，展示调查研究的过程、长冈乡基层政权建设以及苏区干部工作作风。这里特别适合红培课程中的“调查研究”“群众路线”“基层治理”主题，与兴国将军园、潋江书院相比，教学主题更聚焦、研讨属性更强。",
    verificationLevel: "A",
    verificationNote: "兴国县政府博物馆名录明确该馆由兴国革命纪念馆管理并公布统一开放时段。",
    verifiedAt: "2026-08-21",
  },
  XG3: {
    address: "江西省赣州市兴国县潋江镇横街26号（文昌路横街小井头一带）",
    openingHours: "周二至周日 08:30–12:00、14:30–17:30",
    openNote: "周一闭馆",
    reservationRequired: "未见独立网页预约；团队可联系兴国革命纪念馆",
    reservationMethod: "0797-5322604",
    reservationUrl: null,
    officialUrl: "https://www.xingguo.gov.cn/xgxxxgk/xg91019/202406/2c7dcafbb025443b86bde76e93ae04cb.shtml",
    sourceUrl: "https://www.xingguo.gov.cn/xgzf/c114397/list_4.shtml",
    description: "潋江书院是兴国县城重要历史建筑，也是中央苏区时期革命活动的重要旧址。毛泽东曾在兴国开展土地革命、干部教育和调查研究工作，书院与中央苏区早期干部培训活动密切相关，现作为兴国革命纪念馆管理的“土地革命干部训练班旧址”等红色资源组成部分对外展示。传统书院建筑与革命教育史在同一空间叠加，使其既有地方文化价值，也有党史教育价值。参观可重点讲解苏区干部培养、土地政策和调查研究，并与县城内其他旧址组成步行式教学线路。",
    verificationLevel: "A-",
    verificationNote: "县政府名录确认其作为兴国革命纪念馆所辖旧址统一开放；门牌建议上线前再次导航核实。",
    verifiedAt: "2026-08-21",
  },
  ND1: {
    address: "江西省赣州市宁都县梅江街道梅江路一带（宁都起义纪念馆新馆，建议导航馆名）",
    openingHours: "常规参考周二至周日 08:30–11:30、14:30–17:30",
    openNote: "周一一般闭馆；以新馆最新公告为准",
    reservationRequired: "未发现独立网页预约入口",
    reservationMethod: "通常免费参观；团队建议联系宁都县文旅/馆方",
    reservationUrl: null,
    officialUrl: "https://www.ningdu.gov.cn/ndxrmzfyyh/c104221/202512/a39cd1d3b72045bf92c11edc39253e64.shtml",
    sourceUrl: "https://www.celaj.gov.cn/col12/168799.html",
    description: "宁都起义纪念馆以1931年12月发生的宁都起义为主题。原国民党第二十六路军一万七千余人在中国共产党影响和组织下举行起义，随后编入中国工农红军，成为中央苏区军事力量发展史上的重大事件。纪念馆通过人物、部队沿革、起义过程、红军改编和后续战斗等内容，展示宁都起义的历史背景和影响。2025年12月新馆展陈正式开放，意味着旧资料中关于老馆规模、位置和展陈的信息可能已经过时。平台应优先采用新馆状态，并在正式上线前再次核准门牌和最新预约细则。",
    verificationLevel: "B+",
    verificationNote: "2025-12县政府确认新馆开展；公开页面未明确稳定门牌号，故地址需上线前二次核验。",
    verifiedAt: "2026-08-21",
  },
  ND2: {
    address: "江西省赣州市宁都县小布镇小布村赤坎组及周边",
    openingHours: "开放式旧址群，建议 08:30–17:30 白天参观",
    openNote: "无统一闭馆日；个别室内旧址可能有值守时间",
    reservationRequired: "无统一网页预约",
    reservationMethod: "现场参观；团队讲解/教学建议联系小布镇或宁都文旅",
    reservationUrl: null,
    officialUrl: "https://www.ningdu.gov.cn/ndxxxgk/c102274/202507/2f99ca11bddc41cf967d98b43d369307.shtml",
    sourceUrl: "https://www.ningdu.gov.cn/ndxrmzfyyh/c105305/tt.shtml",
    description: "小布红色旧址群位于宁都县小布镇，是中央苏区时期党和红军重要活动区域之一。镇内分布有中共苏区中央局、中央革命军事委员会、红一方面军总司令部、红军无线电侦察等相关旧址，以及朱德等革命领导人活动遗迹，形成较密集的红色旧址网络。与单体纪念馆不同，小布的优势在于“一个红色小镇、多处真实旧址”，可通过步行或短途接驳串联多个历史场景。适合设计2至3小时现场教学，但需要提前确认各旧址是否开门、讲解员调度以及团队车辆停靠位置。",
    verificationLevel: "A-",
    verificationNote: "2025宁都县官方页面可确认小布红色资源和旧址群位置；没有统一门票和预约系统。",
    verifiedAt: "2026-08-21",
  },
  XW1: {
    address: "江西省赣州市寻乌县长宁镇中山路187号",
    openingHours: "周二至周日 08:30–11:30、14:30–17:30",
    openNote: "周一一般闭馆（法定节假日可能调整）",
    reservationRequired: "未发现独立网页预约入口；个人一般免费参观",
    reservationMethod: "团队建议电话咨询0797-2846280",
    reservationUrl: null,
    officialUrl: "https://www.xunwu.gov.cn/xwxxxgk/xwzd67/202505/1a09cf7052b94c91a1e5ce5553985c12.shtml",
    sourceUrl: "https://www.xunwu.gov.cn/xwxxxgk/c116992/202602/f5a7e730bbb740eebe01e6326c9871f5.shtml",
    description: "毛泽东寻乌调查纪念馆是以1930年毛泽东在寻乌开展社会调查并形成《寻乌调查》为核心主题的专题纪念馆。寻乌调查深入考察当地商业、土地关系、社会阶层和城乡经济，为党在革命根据地制定政策和认识中国社会提供了重要实践依据。纪念馆通过历史文献、调查资料、复原场景和专题展览呈现调查过程、方法与成果，并与“寻乌调查·1930”体验项目、培训基地和调查旧址共同形成寻乌调查体验园。其教学价值突出，适合调查研究、实事求是、基层治理等主题课程。",
    verificationLevel: "A-",
    verificationNote: "2025寻乌县政府官方文旅页面确认纪念馆及体验园体系；时段建议出发前电话复核。",
    verifiedAt: "2026-08-21",
  },
  XW2: {
    address: "江西省赣州市寻乌县长宁镇中山路187号毛泽东寻乌调查纪念馆馆区内",
    openingHours: "周二至周日 08:30–11:30、14:30–17:30（随纪念馆）",
    openNote: "周一一般闭馆",
    reservationRequired: "与纪念馆统一管理；未见独立预约入口",
    reservationMethod: "团队建议电话0797-2846280",
    reservationUrl: null,
    officialUrl: "https://www.xunwu.gov.cn/xwxxxgk/xwzd67/202505/1a09cf7052b94c91a1e5ce5553985c12.shtml",
    sourceUrl: "https://www.xunwu.gov.cn/xwxxxgk/c116992/202602/f5a7e730bbb740eebe01e6326c9871f5.shtml",
    description: "毛泽东寻乌调查旧址是1930年毛泽东在寻乌开展深入社会调查和革命实践的重要原址，现纳入毛泽东寻乌调查纪念馆及寻乌调查体验园统一保护利用。旧址的意义在于它不仅纪念一次调查活动，更具体呈现了“到群众中去、掌握真实情况”的工作方法。参观者可将纪念馆中对《寻乌调查》内容、数据和社会结构的系统介绍，与旧址中的真实空间对应起来，从而理解调查研究如何从现场访谈、社会观察转化为政策判断。该点适合作为纪念馆参观后的现场研讨或微党课空间。",
    verificationLevel: "A-",
    verificationNote: "与纪念馆处于同一管理体系和地址片区，建议平台将两点设置父子关系，避免导航重复。",
    verifiedAt: "2026-08-21",
  },
  LS1: {
    address: "江西省九江市庐山风景名胜区河西路504号",
    openingHours: "旺季（3月15日–10月15日）09:00–17:00，16:45停止入馆；淡季（10月16日–次年3月14日）09:00–16:45，16:30停止入馆",
    openNote: "每月第一、第三个星期二闭馆；周末正常开放，法定节假日以公告为准",
    reservationRequired: "未发现旧址独立网页预约；进入庐山景区需遵守庐山景区实名购票/交通规则",
    reservationMethod: "现场参观；可先通过庐山会议旧址纪念馆官网核实公告",
    reservationUrl: null,
    officialUrl: "https://www.lshyjz.com.cn/",
    sourceUrl: "https://www.lushan.gov.cn/bmxzxxgk/bumeng/whgdxwcbj/fdzdgknr_195359/lvyou/202511/t20251114_7061579.html",
    description: "庐山会议旧址位于庐山牯岭河西路，是中华人民共和国成立后重要党史事件的发生地之一。建筑原为庐山大礼堂，后来成为1959年庐山会议及此后相关重要会议的历史见证。现旧址通过会场复原、照片、文献和专题展览呈现会议背景、过程以及庐山在新中国政治史中的特殊地位。与江西其他44点中多数土地革命战争时期旧址相比，庐山会议旧址的年代明显更晚，可帮助路线把江西红色历史从革命战争时期延伸到新中国建设时期。其开放时间采用明确的旺淡季制度，并有固定月度闭馆日。",
    verificationLevel: "A",
    verificationNote: "官网直接公布地址、旺淡季开放时段和每月第一、第三个星期二闭馆规则。",
    verifiedAt: "2026-08-21",
  },
};
